var canvasWidth = 710;
var canvasHeight = 965;
var scale = 1;
var pos = [[10/scale,40/scale],[60/scale + 299, 40/scale]];  // two dimensional array  horiz pos of left edge and vertical pos of bottom in inches
var colorSides = "#0000FF";
var colorEnds = "#FF0000";
var ctx;
var aw = 1.5;  // actual width of boards
var dw = 1.5;    // drawn width of boards
var fw = 20;   // footer width
var b = [];
var s = [];
var pageTitle;
var fId = getUrlParameters("fId");
if(fId == "0"){ fId = "2A16"; }
$(document).ready(function(){
    $("body").append('<canvas id="canvas" width = '+canvasWidth+' height = '+canvasHeight+'></canvas>');
   // $("body").append('<canvas id="canvas" width = '+canvasWidth+' height = '+canvasHeight+' style="border:1px solid #000000"></canvas>');
    var canvas = document.getElementById("canvas");
    if (canvas.getContext) {
        ctx = canvas.getContext("2d");
        loadFooterData(fId);
        ctx.fillStyle = "#000000";
        ctx.textAlign = "center";
        ctx.font = "bold 20px Calibri";
        ctx.fillText(pageTitle,canvasWidth/2,20);
        for(var i = 1; i < b.length; i++){                   // draw horizontal lines first to so vertical lines cover excess due to dw <> aw
            if(b[i].orient == "h" ){ draw0(b[i],0);}
        }
        for(var i = 1; i < b.length; i++){
            if(b[i].orient == "v" ){ draw0(b[i],0);}
            drawTable(b[i],1);
        }
    }
});
function getUrlParameters(name) {
    name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
    var regexS = "[\\?&]" + name + "=([^&#]*)";
    var regex = new RegExp(regexS);
    var results = regex.exec(window.location.href);
    if (results == null)
        return "0";
    else
        return results[1];
}
function draw0(tb,tpos){
     if(tb.orient == "v"){
        var left = (pos[tpos][0] + tb.lpos) * scale ;
        var top = (pos[tpos][1] + tb.vpos) * scale;
        var width = dw * scale;
        var height = tb.len * scale;
        ctx.fillStyle = colorSides;
        var labLeft =left-6;
        var labTop = top + height/2 -10;
        
    } else {
        var left = (pos[tpos][0] + tb.lpos) * scale;
        var top = (pos[tpos][1] + tb.vpos) * scale;
        var width =   tb.len * scale;
        var height = dw * scale;
        ctx.fillStyle = colorEnds;
        var labLeft = left + width/2-10;
        var labTop = top-6;
    }
    ctx.fillRect ( left, top, width, height);
    ctx.fillStyle = "#FFFFFF";
    ctx.fillRect(labLeft,labTop,20,20);
    ctx.strokeRect(labLeft,labTop,20,20);
    ctx.fillStyle = "#000000";
    ctx.font = "bold 16px Calibri";
    ctx.textAlign = "center";
    ctx.fillText(tb.id,labLeft+10,labTop+15);
}
function drawTable(tb,tpos){
    ctx.fillStyle = "#000000";
    ctx.textAlign = "right";
    ctx.font = "16px Calibri";
    ctx.fillText(tb.id, pos[tpos][0] * scale + 40, pos[tpos][1] * scale + 20 * tb.id);
    ctx.fillText(inchesToFeet(tb.len), pos[tpos][0] * scale + 120, pos[tpos][1] * scale + 20 * tb.id);
    ctx.fillText(tb.len + '"', pos[tpos][0] * scale + 200, pos[tpos][1] * scale + 20 * tb.id);
}
function inchesToFeet(x){
    f = Math.floor(x/12);
    i = x % 12;
    i = +(Math.round(i + "e+2") + "e-2");
    return f + "' "+ i +'"';
}
function loadFooterData(footer){
    switch(footer){
        case  "2A16": 
            pageTitle = "2 Bedroom House - Elevation A - 16 inch Footer";
            scale = 1.4;
            dw = 3.5;
            fw = 16;
            b.push( {id:0 }); // dummy 
            b.push( {id: 2,  orient: "h", lpos: aw,                        vpos: 0,                      len: 292   });
            b.push( {id: 4,  orient: "h", lpos: aw * 2 + 130.5 ,           vpos: 499 - dw,               len: 160   });
            b.push( {id: 6,  orient: "h", lpos: aw,                        vpos: 463 - dw,               len: 130.5 });
            b.push( {id: 8,  orient: "h", lpos: aw * 2 + fw,               vpos: aw + fw,                len: 257   });
            b.push( {id: 10, orient: "h", lpos: aw * 3 + fw + 113,         vpos: aw + fw + 380- dw,      len: 142.5 });
            b.push( {id: 12, orient: "h", lpos: aw * 2 + fw,               vpos: aw + fw + 428 - dw,     len: 113   });
            b.push( {id: 14, orient: "h", lpos: aw * 3 + fw + 130.5,       vpos: aw + fw * 2 + 380,      len: 125   });
            b.push( {id: 16, orient: "h", lpos: aw * 3 + fw + 130.5,       vpos: aw + fw * 2 +380+68-dw, len: 125   });
            b.push( {id: 1,  orient: "v", lpos: 0,                         vpos: 0,                      len: 463   });
            b.push( {id: 3,  orient: "v", lpos: aw  + 292,                 vpos: 0,                      len: 499   });
            b.push( {id: 5,  orient: "v", lpos: aw + 130.5,                vpos: 463 - dw,               len: 37.5  });
            b.push( {id: 7,  orient: "v", lpos: aw + fw,                   vpos: aw + fw,                len: 428   });
            b.push( {id: 9,  orient: "v", lpos: aw * 2 + fw +257,          vpos: aw + fw,                len: 380   });
            b.push( {id: 11, orient: "v", lpos: aw * 2 + fw + 113,         vpos: aw + fw + 380 - dw,     len: 49.5  });
            b.push( {id: 13, orient: "v", lpos: aw * 2 + fw + 130.5,       vpos: aw + fw * 2 + 380,      len: 68    });
            b.push( {id: 15, orient: "v", lpos: aw * 3 + fw + 130.5 + 125, vpos: aw + fw * 2 + 380,      len: 68    });
            break;
        case  "2A20": 
            pageTitle = "2 Bedroom House - Elevation A - 20 inch Footer";
            scale = 1.4;
            dw = 3.5;
            fw = 20;
            b.push( {id:0 }); // dummy 
            b.push( {id: 2,  orient: "h", lpos: aw,                        vpos: 0,                      len: 296   });
            b.push( {id: 4,  orient: "h", lpos: aw * 2 + 130.5 ,           vpos: 503 - dw,               len: 164   });
            b.push( {id: 6,  orient: "h", lpos: aw,                        vpos: 467 - dw,               len: 130.5 });
            b.push( {id: 8,  orient: "h", lpos: aw * 2 + fw,               vpos: aw + fw,                len: 253   });
            b.push( {id: 10, orient: "h", lpos: aw * 3 + fw + 109,         vpos: aw + fw + 376- dw,      len: 142.5 });
            b.push( {id: 12, orient: "h", lpos: aw * 2 + fw,               vpos: aw + fw + 424 - dw,     len: 109   });
            b.push( {id: 14, orient: "h", lpos: aw * 3 + fw + 130.5,       vpos: aw + fw *2 + 376 ,      len: 121   });
            b.push( {id: 16, orient: "h", lpos: aw * 3 + fw + 130.5,       vpos: aw + fw * 2+376+64- dw, len: 121   });
            b.push( {id: 1,  orient: "v", lpos: 0,                         vpos: 0,                      len: 467   });
            b.push( {id: 3,  orient: "v", lpos: aw  + 296,                 vpos: 0,                      len: 503   });
            b.push( {id: 5,  orient: "v", lpos: aw + 130.5,                vpos: 467 - dw,               len: 37.5  });
            b.push( {id: 7,  orient: "v", lpos: aw + fw,                   vpos: aw + fw,                len: 424   });
            b.push( {id: 9,  orient: "v", lpos: aw * 2 + fw +253,          vpos: aw + fw,                len: 376   });
            b.push( {id: 11, orient: "v", lpos: aw * 2 + fw + 109,         vpos: aw + fw +  376 - dw,    len: 49.5  });
            b.push( {id: 13, orient: "v", lpos: aw * 2 + fw + 130.5,       vpos: aw + fw * 2  + 376 ,    len: 64    });
            b.push( {id: 15, orient: "v", lpos: aw * 3 + fw + 130.5 + 121, vpos: aw + fw * 2 + 376 ,     len: 64    });
            break;
        case "3A16": 
            pageTitle = "3 Bedroom House - Elevation A - 16 inch Footer";
            scale = 1.4;
            dw = 3.5;
            fw = 16;
            b.push( {id:0 }); // dummy 
            b.push( {id: 1,  orient: "v", len: 535,   lpos: 0,                                     vpos: 0                                   });
            b.push( {id: 2,  orient: "h", len: 292,   lpos: aw,                                    vpos: 0                                   });
            b.push( {id: 3,  orient: "v", len: 571,   lpos: aw + b[2].len,                         vpos: 0                                   });
            b.push( {id: 4,  orient: "h", len: 130.5, lpos: aw,                                    vpos: b[1].len - dw                       });
            b.push( {id: 5,  orient: "v", len: 226,   lpos: aw + fw,                               vpos: aw + fw                             });
            b.push( {id: 6,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len - dw             });
            b.push( {id: 7,  orient: "v", len: 48,    lpos: aw * 2 + fw + b[6].len - dw,           vpos: aw + fw + b[5].len                  });
            b.push( {id: 8,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 9,  orient: "v", len: 226,   lpos: aw + fw,                               vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 10, orient: "h", len: 257,   lpos: aw * 2 + fw,                           vpos: aw + fw                             });
            b.push( {id: 11, orient: "v", len: 202,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw                             });
            b.push( {id: 12, orient: "h", len: 48,                                                 vpos: aw + fw + b[11].len - dw            });
                                                b[12].lpos = aw * 2 + fw + b[10].len - b[12].len;  
            b.push( {id: 13, orient: "v", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len                 });
            b.push( {id: 14, orient: "h", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 15, orient: "v", len: 202,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 16, orient: "h", len: 113,   lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len + b[9].len - dw    });
            b.push( {id: 17, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len + b[15].len - dw });
            b.push( {id: 18, orient: "h", len: 142.5, lpos: aw * 3 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len+ b[15].len - dw  });
            b.push( {id: 19, orient: "v", len: 37.5,  lpos: aw + b[4].len,                         vpos: b[1].len - dw                                    });
            b.push( {id: 20, orient: "h", len: 160,   lpos: aw * 2 + b[4].len,                     vpos: b[3].len - dw                                    });
            b.push( {id: 21, orient: "v", len: 68,    lpos: aw * 2 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 22, orient: "h", len: 125,   lpos: aw * 3 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 23, orient: "v", len: 68,    lpos: aw * 3 + fw + b[4].len + b[22].len,    vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 24, orient: "h", len: 125,   lpos: aw * 3 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len + b[23].len - dw });
            b.push( {id: 25, orient: "v", len: 39 });
            b.push( {id: 26, orient: "h", len: 36 });
            b.push( {id: 27, orient: "v", len: 39 });
            b.push( {id: 28, orient: "h", len: 36 });
            b.push( {id: 29, orient: "v", len: 39 });
            b.push( {id: 30, orient: "h", len: 36 });
            b.push( {id: 31, orient: "v", len: 39 });
            b.push( {id: 32, orient: "h", len: 36 });
            var hspace = (b[10].len - b[26].len - aw * 2) / 2;
            var vspace = (b[11].len + b[13].len + b[15].len - aw * 2 - b[25].len - b[27].len ) / 3;
            b[25].lpos = aw * 2 + fw + hspace;                    b[25].vpos = aw * 2 + fw + vspace;
            b[26].lpos = aw * 3 + fw + hspace;                    b[26].vpos = aw * 2 + fw + vspace;
            b[27].lpos = aw * 3 + fw + hspace + b[26].len;        b[27].vpos = aw * 2 + fw + vspace;
            b[28].lpos = aw * 3 + fw + hspace;                    b[28].vpos = aw * 2 + fw + vspace + b[25].len - dw;
            b[29].lpos = aw * 2 + fw + hspace;                    b[29].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[30].lpos = aw * 3 + fw + hspace;                    b[30].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[31].lpos = aw * 3 + fw + hspace + b[30].len;        b[31].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[32].lpos = aw * 3 + fw + hspace;                    b[32].vpos = aw * 2 + fw + vspace * 2 + b[25].len + b[29].len - dw ;
            break;
        case "3A20": 
            pageTitle = "3 Bedroom House - Elevation A - 20 inch Footer";
            scale = 1.4;
            dw = 3.5;
            fw = 20;
            b.push( {id:0 }); // dummy 
            b.push( {id: 1,  orient: "v", len: 539,   lpos: 0,                                     vpos: 0                                   });
            b.push( {id: 2,  orient: "h", len: 296,   lpos: aw,                                    vpos: 0                                   });
            b.push( {id: 3,  orient: "v", len: 575,   lpos: aw + b[2].len,                         vpos: 0                                   });
            b.push( {id: 4,  orient: "h", len: 130.5, lpos: aw,                                    vpos: b[1].len - dw                       });
            b.push( {id: 5,  orient: "v", len: 224,   lpos: aw + fw,                               vpos: aw + fw                             });
            b.push( {id: 6,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len - dw             });
            b.push( {id: 7,  orient: "v", len: 48,    lpos: aw * 2 + fw + b[6].len - dw,           vpos: aw + fw + b[5].len                  });
            b.push( {id: 8,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 9,  orient: "v", len: 224,   lpos: aw + fw,                               vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 10, orient: "h", len: 253,   lpos: aw * 2 + fw,                           vpos: aw + fw                             });
            b.push( {id: 11, orient: "v", len: 200,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw                             });
            b.push( {id: 12, orient: "h", len: 48,                                                 vpos: aw + fw + b[11].len - dw            });
                                                b[12].lpos = aw * 2 + fw + b[10].len - b[12].len;  
            b.push( {id: 13, orient: "v", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len                 });
            b.push( {id: 14, orient: "h", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 15, orient: "v", len: 200,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 16, orient: "h", len: 109,   lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len + b[9].len - dw    });
            b.push( {id: 17, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len + b[15].len - dw });
            b.push( {id: 18, orient: "h", len: 142.5, lpos: aw * 3 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len+ b[15].len - dw  });
            b.push( {id: 19, orient: "v", len: 37.5,  lpos: aw + b[4].len,                         vpos: b[1].len - dw                                    });
            b.push( {id: 20, orient: "h", len: 164,   lpos: aw * 2 + b[4].len,                     vpos: b[3].len - dw                                    });
            b.push( {id: 21, orient: "v", len: 64,    lpos: aw * 2 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 22, orient: "h", len: 121,   lpos: aw * 3 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 23, orient: "v", len: 64,    lpos: aw * 3 + fw + b[4].len + b[22].len,    vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 24, orient: "h", len: 121,   lpos: aw * 3 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len + b[23].len - dw });
            b.push( {id: 25, orient: "v", len: 39 });
            b.push( {id: 26, orient: "h", len: 36 });
            b.push( {id: 27, orient: "v", len: 39 });
            b.push( {id: 28, orient: "h", len: 36 });
            b.push( {id: 29, orient: "v", len: 39 });
            b.push( {id: 30, orient: "h", len: 36 });
            b.push( {id: 31, orient: "v", len: 39 });
            b.push( {id: 32, orient: "h", len: 36 });
            var hspace = (b[10].len - b[26].len - aw * 2) / 2;
            var vspace = (b[11].len + b[13].len + b[15].len - aw * 2 - b[25].len - b[27].len ) / 3;
            b[25].lpos = aw * 2 + fw + hspace;                    b[25].vpos = aw * 2 + fw + vspace;
            b[26].lpos = aw * 3 + fw + hspace;                    b[26].vpos = aw * 2 + fw + vspace;
            b[27].lpos = aw * 3 + fw + hspace + b[26].len;        b[27].vpos = aw * 2 + fw + vspace;
            b[28].lpos = aw * 3 + fw + hspace;                    b[28].vpos = aw * 2 + fw + vspace + b[25].len - dw;
            b[29].lpos = aw * 2 + fw + hspace;                    b[29].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[30].lpos = aw * 3 + fw + hspace;                    b[30].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[31].lpos = aw * 3 + fw + hspace + b[30].len;        b[31].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[32].lpos = aw * 3 + fw + hspace;                    b[32].vpos = aw * 2 + fw + vspace * 2 + b[25].len + b[29].len - dw ;
           break;
        case "3B16": 
            pageTitle = "3 Bedroom House - Elevation B - 16 inch Footer";
            scale = 1.4;
            dw = 3.5;
            fw = 16;
            b.push( {id:0 }); // dummy 
            b.push( {id: 1,  orient: "v", len: 571,   lpos: 0,                                     vpos: 0                                   });
            b.push( {id: 2,  orient: "h", len: 292,   lpos: aw,                                    vpos: 0                                   });
            b.push( {id: 3,  orient: "v", len: 571,   lpos: aw + b[2].len,                         vpos: 0                                   });
            b.push( {id: 4,  orient: "h", len: 292,   lpos: aw,                                    vpos: b[1].len - dw                       });
            b.push( {id: 5,  orient: "v", len: 226,   lpos: aw + fw,                               vpos: aw + fw                             });
            b.push( {id: 6,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len - dw             });
            b.push( {id: 7,  orient: "v", len: 48,    lpos: aw * 2 + fw + b[6].len - dw,           vpos: aw + fw + b[5].len                  });
            b.push( {id: 8,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 9,  orient: "v", len: 226,   lpos: aw + fw,                               vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 10, orient: "h", len: 257,   lpos: aw * 2 + fw,                           vpos: aw + fw                             });
            b.push( {id: 11, orient: "v", len: 202,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw                             });
            b.push( {id: 12, orient: "h", len: 48,                                                 vpos: aw + fw + b[11].len - dw            });
                                                b[12].lpos = aw * 2 + fw + b[10].len - b[12].len;  
            b.push( {id: 13, orient: "v", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len                 });
            b.push( {id: 14, orient: "h", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 15, orient: "v", len: 202,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 16, orient: "h", len: 113,   lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len + b[9].len - dw    });
            b.push( {id: 17, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len + b[15].len - dw });
            b.push( {id: 18, orient: "h", len: 142.5, lpos: aw * 3 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len+ b[15].len - dw  });
            b.push( {id: 19, orient: "v", len: 20,    lpos: aw + fw,                               vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len     });
            b.push( {id: 20, orient: "h", len: 130.5, lpos: aw * 2 + fw,                           vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len     });
            b.push( {id: 21, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[20].len,               vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 22, orient: "h", len: 125,   lpos: aw * 3 + fw + b[20].len,               vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 23, orient: "v", len: 68,    lpos: aw * 3 + fw + b[20].len + b[22].len,   vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 24, orient: "h", len: 257,   lpos: aw * 2 + fw,                           vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len + b[19].len - dw });
            b.push( {id: 25, orient: "v", len: 39 });
            b.push( {id: 26, orient: "h", len: 36 });
            b.push( {id: 27, orient: "v", len: 39 });
            b.push( {id: 28, orient: "h", len: 36 });
            b.push( {id: 29, orient: "v", len: 39 });
            b.push( {id: 30, orient: "h", len: 36 });
            b.push( {id: 31, orient: "v", len: 39 });
            b.push( {id: 32, orient: "h", len: 36 });
            var hspace = (b[10].len - b[26].len - aw * 2) / 2;
            var vspace = (b[11].len + b[13].len + b[15].len - aw * 2 - b[25].len - b[27].len ) / 3;
            b[25].lpos = aw * 2 + fw + hspace;                    b[25].vpos = aw * 2 + fw + vspace;
            b[26].lpos = aw * 3 + fw + hspace;                    b[26].vpos = aw * 2 + fw + vspace;
            b[27].lpos = aw * 3 + fw + hspace + b[26].len;        b[27].vpos = aw * 2 + fw + vspace;
            b[28].lpos = aw * 3 + fw + hspace;                    b[28].vpos = aw * 2 + fw + vspace + b[25].len - dw;
            b[29].lpos = aw * 2 + fw + hspace;                    b[29].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[30].lpos = aw * 3 + fw + hspace;                    b[30].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[31].lpos = aw * 3 + fw + hspace + b[30].len;        b[31].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[32].lpos = aw * 3 + fw + hspace;                    b[32].vpos = aw * 2 + fw + vspace * 2 + b[25].len + b[29].len - dw ;
            break;
        case "3B20": 
            pageTitle = "3 Bedroom House - Elevation B - 20 inch Footer";
            scale = 1.4;
            dw = 3.5;
            fw = 20;
            b.push( {id:0 }); // dummy 
            b.push( {id: 1,  orient: "v", len: 575,   lpos: 0,                                     vpos: 0                                   });
            b.push( {id: 2,  orient: "h", len: 296,   lpos: aw,                                    vpos: 0                                   });
            b.push( {id: 3,  orient: "v", len: 575,   lpos: aw + b[2].len,                         vpos: 0                                   });
            b.push( {id: 4,  orient: "h", len: 296,   lpos: aw,                                    vpos: b[1].len - dw                       });
            b.push( {id: 5,  orient: "v", len: 224,   lpos: aw + fw,                               vpos: aw + fw                             });
            b.push( {id: 6,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len - dw             });
            b.push( {id: 7,  orient: "v", len: 48,    lpos: aw * 2 + fw + b[6].len - dw,           vpos: aw + fw + b[5].len                  });
            b.push( {id: 8,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 9,  orient: "v", len: 224,   lpos: aw + fw,                               vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 10, orient: "h", len: 253,   lpos: aw * 2 + fw,                           vpos: aw + fw                             });
            b.push( {id: 11, orient: "v", len: 200,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw                             });
            b.push( {id: 12, orient: "h", len: 48,                                                 vpos: aw + fw + b[11].len - dw            });
                                                b[12].lpos = aw * 2 + fw + b[10].len - b[12].len;  
            b.push( {id: 13, orient: "v", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len                 });
            b.push( {id: 14, orient: "h", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 15, orient: "v", len: 200,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 16, orient: "h", len: 109,   lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len + b[9].len - dw    });
            b.push( {id: 17, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len + b[15].len - dw });
            b.push( {id: 18, orient: "h", len: 142.5, lpos: aw * 3 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len+ b[15].len - dw  });
            b.push( {id: 19, orient: "v", len: 16,    lpos: aw + fw,                               vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len     });
            b.push( {id: 20, orient: "h", len: 130.5, lpos: aw * 2 + fw,                           vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len     });
            b.push( {id: 21, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[20].len,               vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 22, orient: "h", len: 121,   lpos: aw * 3 + fw + b[20].len,               vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 23, orient: "v", len: 64,    lpos: aw * 3 + fw + b[20].len + b[22].len,   vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 24, orient: "h", len: 253,   lpos: aw * 2 + fw,                           vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len + b[19].len - dw });
            b.push( {id: 25, orient: "v", len: 39 });
            b.push( {id: 26, orient: "h", len: 36 });
            b.push( {id: 27, orient: "v", len: 39 });
            b.push( {id: 28, orient: "h", len: 36 });
            b.push( {id: 29, orient: "v", len: 39 });
            b.push( {id: 30, orient: "h", len: 36 });
            b.push( {id: 31, orient: "v", len: 39 });
            b.push( {id: 32, orient: "h", len: 36 });
            var hspace = (b[10].len - b[26].len - aw * 2) / 2;
            var vspace = (b[11].len + b[13].len + b[15].len - aw * 2 - b[25].len - b[27].len ) / 3;
            b[25].lpos = aw * 2 + fw + hspace;                    b[25].vpos = aw * 2 + fw + vspace;
            b[26].lpos = aw * 3 + fw + hspace;                    b[26].vpos = aw * 2 + fw + vspace;
            b[27].lpos = aw * 3 + fw + hspace + b[26].len;        b[27].vpos = aw * 2 + fw + vspace;
            b[28].lpos = aw * 3 + fw + hspace;                    b[28].vpos = aw * 2 + fw + vspace + b[25].len - dw;
            b[29].lpos = aw * 2 + fw + hspace;                    b[29].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[30].lpos = aw * 3 + fw + hspace;                    b[30].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[31].lpos = aw * 3 + fw + hspace + b[30].len;        b[31].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[32].lpos = aw * 3 + fw + hspace;                    b[32].vpos = aw * 2 + fw + vspace * 2 + b[25].len + b[29].len - dw ;
            break;
        case "4A16": 
            pageTitle = "4 Bedroom House - Elevation A - 16 inch Footer";
            scale = 1.25;
            dw = 3.5;
            fw = 16;
            b.push( {id:0 }); // dummy 
            b.push( {id: 1,  orient: "v", len: 608,   lpos: 0,                                     vpos: 0                                   });
            b.push( {id: 2,  orient: "h", len: 292,   lpos: aw,                                    vpos: 0                                   });
            b.push( {id: 3,  orient: "v", len: 644,   lpos: aw + b[2].len,                         vpos: 0                                   });
            b.push( {id: 4,  orient: "h", len: 130.5, lpos: aw,                                    vpos: b[1].len - dw                       });
            b.push( {id: 5,  orient: "v", len: 262,   lpos: aw + fw,                               vpos: aw + fw                             });
            b.push( {id: 6,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len - dw             });
            b.push( {id: 7,  orient: "v", len: 48,    lpos: aw * 2 + fw + b[6].len - dw,           vpos: aw + fw + b[5].len                  });
            b.push( {id: 8,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 9,  orient: "v", len: 262,   lpos: aw + fw,                               vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 10, orient: "h", len: 257,   lpos: aw * 2 + fw,                           vpos: aw + fw                             });
            b.push( {id: 11, orient: "v", len: 238,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw                             });
            b.push( {id: 12, orient: "h", len: 48,                                                 vpos: aw + fw + b[11].len - dw            });
                                                b[12].lpos = aw * 2 + fw + b[10].len - b[12].len;  
            b.push( {id: 13, orient: "v", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len                 });
            b.push( {id: 14, orient: "h", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 15, orient: "v", len: 238,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 16, orient: "h", len: 113,   lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len + b[9].len - dw    });
            b.push( {id: 17, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len + b[15].len - dw });
            b.push( {id: 18, orient: "h", len: 142.5, lpos: aw * 3 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len+ b[15].len - dw  });
            b.push( {id: 19, orient: "v", len: 37.5,  lpos: aw + b[4].len,                         vpos: b[1].len - dw                                    });
            b.push( {id: 20, orient: "h", len: 160,   lpos: aw * 2 + b[4].len,                     vpos: b[3].len - dw                                    });
            b.push( {id: 21, orient: "v", len: 68,    lpos: aw * 2 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 22, orient: "h", len: 125,   lpos: aw * 3 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 23, orient: "v", len: 68,    lpos: aw * 3 + fw + b[4].len + b[22].len,    vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 24, orient: "h", len: 125,   lpos: aw * 3 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len + b[23].len - dw });
            b.push( {id: 25, orient: "v", len: 39 });
            b.push( {id: 26, orient: "h", len: 36 });
            b.push( {id: 27, orient: "v", len: 39 });
            b.push( {id: 28, orient: "h", len: 36 });
            b.push( {id: 29, orient: "v", len: 39 });
            b.push( {id: 30, orient: "h", len: 36 });
            b.push( {id: 31, orient: "v", len: 39 });
            b.push( {id: 32, orient: "h", len: 36 });
            var hspace = (b[10].len - b[26].len - aw * 2) / 2;
            var vspace = (b[11].len + b[13].len + b[15].len - aw * 2 - b[25].len - b[27].len ) / 3;
            b[25].lpos = aw * 2 + fw + hspace;                    b[25].vpos = aw * 2 + fw + vspace;
            b[26].lpos = aw * 3 + fw + hspace;                    b[26].vpos = aw * 2 + fw + vspace;
            b[27].lpos = aw * 3 + fw + hspace + b[26].len;        b[27].vpos = aw * 2 + fw + vspace;
            b[28].lpos = aw * 3 + fw + hspace;                    b[28].vpos = aw * 2 + fw + vspace + b[25].len - dw;
            b[29].lpos = aw * 2 + fw + hspace;                    b[29].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[30].lpos = aw * 3 + fw + hspace;                    b[30].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[31].lpos = aw * 3 + fw + hspace + b[30].len;        b[31].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[32].lpos = aw * 3 + fw + hspace;                    b[32].vpos = aw * 2 + fw + vspace * 2 + b[25].len + b[29].len - dw ;
            break;
        case "4A20": 
            pageTitle = "4 Bedroom House - Elevation A - 20 inch Footer";
            scale = 1.25;
            dw = 3.5;
            fw = 20;
            b.push( {id:0 }); // dummy 
            b.push( {id: 1,  orient: "v", len: 611,   lpos: 0,                                     vpos: 0                                   });
            b.push( {id: 2,  orient: "h", len: 296,   lpos: aw,                                    vpos: 0                                   });
            b.push( {id: 3,  orient: "v", len: 647,   lpos: aw + b[2].len,                         vpos: 0                                   });
            b.push( {id: 4,  orient: "h", len: 130.5, lpos: aw,                                    vpos: b[1].len - dw                       });
            b.push( {id: 5,  orient: "v", len: 260,   lpos: aw + fw,                               vpos: aw + fw                             });
            b.push( {id: 6,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len - dw             });
            b.push( {id: 7,  orient: "v", len: 48,    lpos: aw * 2 + fw + b[6].len - dw,           vpos: aw + fw + b[5].len                  });
            b.push( {id: 8,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 9,  orient: "v", len: 260,   lpos: aw + fw,                               vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 10, orient: "h", len: 253,   lpos: aw * 2 + fw,                           vpos: aw + fw                             });
            b.push( {id: 11, orient: "v", len: 236,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw                             });
            b.push( {id: 12, orient: "h", len: 48,                                                 vpos: aw + fw + b[11].len - dw            });
                                                b[12].lpos = aw * 2 + fw + b[10].len - b[12].len;  
            b.push( {id: 13, orient: "v", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len                 });
            b.push( {id: 14, orient: "h", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 15, orient: "v", len: 236,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 16, orient: "h", len: 109,   lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len + b[9].len - dw    });
            b.push( {id: 17, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len + b[15].len - dw });
            b.push( {id: 18, orient: "h", len: 142.5, lpos: aw * 3 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len+ b[15].len - dw  });
            b.push( {id: 19, orient: "v", len: 37.5,  lpos: aw + b[4].len,                         vpos: b[1].len - dw                                    });
            b.push( {id: 20, orient: "h", len: 164,   lpos: aw * 2 + b[4].len,                     vpos: b[3].len - dw                                    });
            b.push( {id: 21, orient: "v", len: 64,    lpos: aw * 2 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 22, orient: "h", len: 121,   lpos: aw * 3 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 23, orient: "v", len: 64,    lpos: aw * 3 + fw + b[4].len + b[22].len,    vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 24, orient: "h", len: 121,   lpos: aw * 3 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len + b[23].len - dw });
            b.push( {id: 25, orient: "v", len: 37 });
            b.push( {id: 26, orient: "h", len: 34 });
            b.push( {id: 27, orient: "v", len: 37 });
            b.push( {id: 28, orient: "h", len: 34 });
            b.push( {id: 29, orient: "v", len: 37 });
            b.push( {id: 30, orient: "h", len: 34 });
            b.push( {id: 31, orient: "v", len: 37 });
            b.push( {id: 32, orient: "h", len: 34 });
            b.push( {id: 33, orient: "v", len: 37 });
            b.push( {id: 34, orient: "h", len: 34 });
            b.push( {id: 35, orient: "v", len: 37 });
            b.push( {id: 36, orient: "h", len: 34 });
            var hspace = (b[10].len - b[26].len - aw * 2) / 2;
            var vspace = (b[11].len + b[13].len + b[15].len - aw * 2 - b[25].len - b[27].len - b[29].len) / 4;
            b[25].lpos = aw * 2 + fw + hspace;                    b[25].vpos = aw * 2 + fw + vspace;
            b[26].lpos = aw * 3 + fw + hspace;                    b[26].vpos = aw * 2 + fw + vspace;
            b[27].lpos = aw * 3 + fw + hspace + b[26].len;        b[27].vpos = aw * 2 + fw + vspace;
            b[28].lpos = aw * 3 + fw + hspace;                    b[28].vpos = aw * 2 + fw + vspace + b[25].len - dw;
            b[29].lpos = aw * 2 + fw + hspace;                    b[29].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[30].lpos = aw * 3 + fw + hspace;                    b[30].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[31].lpos = aw * 3 + fw + hspace + b[30].len;        b[31].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[32].lpos = aw * 3 + fw + hspace;                    b[32].vpos = aw * 2 + fw + vspace * 2 + b[25].len + b[29].len - dw ;
            b[33].lpos = aw * 2 + fw + hspace;                    b[33].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[34].lpos = aw * 3 + fw + hspace;                    b[34].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[35].lpos = aw * 3 + fw + hspace + b[34].len;        b[35].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[36].lpos = aw * 3 + fw + hspace;                    b[36].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len + b[33].len - dw ;
            break;
        case "4B16": 
            pageTitle = "4 Bedroom House - Elevation B - 16 inch Footer";
            scale = 1.25;
            dw = 3.5;
            fw = 16;
            b.push( {id:0 }); // dummy 
            b.push( {id: 1,  orient: "v", len: 644,   lpos: 0,                                     vpos: 0                                   });
            b.push( {id: 2,  orient: "h", len: 292,   lpos: aw,                                    vpos: 0                                   });
            b.push( {id: 3,  orient: "v", len: 644,   lpos: aw + b[2].len,                         vpos: 0                                   });
            b.push( {id: 4,  orient: "h", len: 292,   lpos: aw,                                    vpos: b[1].len - dw                       });
            b.push( {id: 5,  orient: "v", len: 262,   lpos: aw + fw,                               vpos: aw + fw                             });
            b.push( {id: 6,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len - dw             });
            b.push( {id: 7,  orient: "v", len: 48,    lpos: aw * 2 + fw + b[6].len - dw,           vpos: aw + fw + b[5].len                  });
            b.push( {id: 8,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 9,  orient: "v", len: 262,   lpos: aw + fw,                               vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 10, orient: "h", len: 257,   lpos: aw * 2 + fw,                           vpos: aw + fw                             });
            b.push( {id: 11, orient: "v", len: 238,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw                             });
            b.push( {id: 12, orient: "h", len: 48,                                                 vpos: aw + fw + b[11].len - dw            });
                                                b[12].lpos = aw * 2 + fw + b[10].len - b[12].len;  
            b.push( {id: 13, orient: "v", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len                 });
            b.push( {id: 14, orient: "h", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 15, orient: "v", len: 238,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 16, orient: "h", len: 113,   lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len + b[9].len - dw    });
            b.push( {id: 17, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len + b[15].len - dw });
            b.push( {id: 18, orient: "h", len: 142.5, lpos: aw * 3 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len+ b[15].len - dw  });
            b.push( {id: 19, orient: "v", len: 20,    lpos: aw + fw,                               vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len     });
            b.push( {id: 20, orient: "h", len: 130.5, lpos: aw * 2 + fw,                           vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len     });
            b.push( {id: 21, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[20].len,               vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 22, orient: "h", len: 125,   lpos: aw * 3 + fw + b[20].len,               vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 23, orient: "v", len: 68,    lpos: aw * 3 + fw + b[20].len + b[22].len,   vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 24, orient: "h", len: 257,   lpos: aw * 2 + fw,                           vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len + b[19].len - dw });
            b.push( {id: 25, orient: "v", len: 39 });
            b.push( {id: 26, orient: "h", len: 36 });
            b.push( {id: 27, orient: "v", len: 39 });
            b.push( {id: 28, orient: "h", len: 36 });
            b.push( {id: 29, orient: "v", len: 39 });
            b.push( {id: 30, orient: "h", len: 36 });
            b.push( {id: 31, orient: "v", len: 39 });
            b.push( {id: 32, orient: "h", len: 36 });
            var hspace = (b[10].len - b[26].len - aw * 2) / 2;
            var vspace = (b[11].len + b[13].len + b[15].len - aw * 2 - b[25].len - b[27].len ) / 3;
            b[25].lpos = aw * 2 + fw + hspace;                    b[25].vpos = aw * 2 + fw + vspace;
            b[26].lpos = aw * 3 + fw + hspace;                    b[26].vpos = aw * 2 + fw + vspace;
            b[27].lpos = aw * 3 + fw + hspace + b[26].len;        b[27].vpos = aw * 2 + fw + vspace;
            b[28].lpos = aw * 3 + fw + hspace;                    b[28].vpos = aw * 2 + fw + vspace + b[25].len - dw;
            b[29].lpos = aw * 2 + fw + hspace;                    b[29].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[30].lpos = aw * 3 + fw + hspace;                    b[30].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[31].lpos = aw * 3 + fw + hspace + b[30].len;        b[31].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[32].lpos = aw * 3 + fw + hspace;                    b[32].vpos = aw * 2 + fw + vspace * 2 + b[25].len + b[29].len - dw ;
            break;
       case "4B20": 
            pageTitle = "4 Bedroom House - Elevation B - 20 inch Footer";
            scale = 1.25;
            dw = 3.5;
            fw = 20;
            b.push( {id:0 }); // dummy 
            b.push( {id: 1,  orient: "v", len: 647,   lpos: 0,                                     vpos: 0                                   });
            b.push( {id: 2,  orient: "h", len: 296,   lpos: aw,                                    vpos: 0                                   });
            b.push( {id: 3,  orient: "v", len: 647,   lpos: aw + b[2].len,                         vpos: 0                                   });
            b.push( {id: 4,  orient: "h", len: 296,   lpos: aw,                                    vpos: b[1].len - dw                       });
            b.push( {id: 5,  orient: "v", len: 260,   lpos: aw + fw,                               vpos: aw + fw                             });
            b.push( {id: 6,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len - dw             });
            b.push( {id: 7,  orient: "v", len: 48,    lpos: aw * 2 + fw + b[6].len - dw,           vpos: aw + fw + b[5].len                  });
            b.push( {id: 8,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 9,  orient: "v", len: 260,   lpos: aw + fw,                               vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 10, orient: "h", len: 253,   lpos: aw * 2 + fw,                           vpos: aw + fw                             });
            b.push( {id: 11, orient: "v", len: 236,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw                             });
            b.push( {id: 12, orient: "h", len: 48,                                                 vpos: aw + fw + b[11].len - dw            });
                                                b[12].lpos = aw * 2 + fw + b[10].len - b[12].len;  
            b.push( {id: 13, orient: "v", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len                 });
            b.push( {id: 14, orient: "h", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 15, orient: "v", len: 236,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 16, orient: "h", len: 109,   lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len + b[9].len - dw    });
            b.push( {id: 17, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len + b[15].len - dw });
            b.push( {id: 18, orient: "h", len: 142.5, lpos: aw * 3 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len+ b[15].len - dw  });
            b.push( {id: 19, orient: "v", len: 16,    lpos: aw + fw,                               vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len     });
            b.push( {id: 20, orient: "h", len: 130.5, lpos: aw * 2 + fw,                           vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len     });
            b.push( {id: 21, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[20].len,               vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 22, orient: "h", len: 121,   lpos: aw * 3 + fw + b[20].len,               vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 23, orient: "v", len: 64,    lpos: aw * 3 + fw + b[20].len + b[22].len,   vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 24, orient: "h", len: 253,   lpos: aw * 2 + fw,                           vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len + b[19].len - dw });
            b.push( {id: 25, orient: "v", len: 37 });
            b.push( {id: 26, orient: "h", len: 34 });
            b.push( {id: 27, orient: "v", len: 37 });
            b.push( {id: 28, orient: "h", len: 34 });
            b.push( {id: 29, orient: "v", len: 37 });
            b.push( {id: 30, orient: "h", len: 34 });
            b.push( {id: 31, orient: "v", len: 37 });
            b.push( {id: 32, orient: "h", len: 34 });
            b.push( {id: 33, orient: "v", len: 37 });
            b.push( {id: 34, orient: "h", len: 34 });
            b.push( {id: 35, orient: "v", len: 37 });
            b.push( {id: 36, orient: "h", len: 34 });
            var hspace = (b[10].len - b[26].len - aw * 2) / 2;
            var vspace = (b[11].len + b[13].len + b[15].len - aw * 2 - b[25].len - b[27].len - b[29].len) / 4;
            b[25].lpos = aw * 2 + fw + hspace;                    b[25].vpos = aw * 2 + fw + vspace;
            b[26].lpos = aw * 3 + fw + hspace;                    b[26].vpos = aw * 2 + fw + vspace;
            b[27].lpos = aw * 3 + fw + hspace + b[26].len;        b[27].vpos = aw * 2 + fw + vspace;
            b[28].lpos = aw * 3 + fw + hspace;                    b[28].vpos = aw * 2 + fw + vspace + b[25].len - dw;
            b[29].lpos = aw * 2 + fw + hspace;                    b[29].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[30].lpos = aw * 3 + fw + hspace;                    b[30].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[31].lpos = aw * 3 + fw + hspace + b[30].len;        b[31].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[32].lpos = aw * 3 + fw + hspace;                    b[32].vpos = aw * 2 + fw + vspace * 2 + b[25].len + b[29].len - dw ;
            b[33].lpos = aw * 2 + fw + hspace;                    b[33].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[34].lpos = aw * 3 + fw + hspace;                    b[34].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[35].lpos = aw * 3 + fw + hspace + b[34].len;        b[35].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[36].lpos = aw * 3 + fw + hspace;                    b[36].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len + b[33].len - dw ;
            break;
        case "5A16": 
            pageTitle = "5 Bedroom House - Elevation A - 16 inch Footer";
            scale = 1.25;
            dw = 3.5;
            fw = 16;
            b.push( {id:0 }); // dummy 
            b.push( {id: 1,  orient: "v", len: 655,   lpos: 0,                                     vpos: 0                                   });
            b.push( {id: 2,  orient: "h", len: 340,   lpos: aw,                                    vpos: 0                                   });
            b.push( {id: 3,  orient: "v", len: 691,   lpos: aw + b[2].len,                         vpos: 0                                   });
            b.push( {id: 4,  orient: "h", len: 130.5, lpos: aw,                                    vpos: b[1].len - dw                       });
            b.push( {id: 5,  orient: "v", len: 286,   lpos: aw + fw,                               vpos: aw + fw                             });
            b.push( {id: 6,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len - dw             });
            b.push( {id: 7,  orient: "v", len: 48,    lpos: aw * 2 + fw + b[6].len - dw,           vpos: aw + fw + b[5].len                  });
            b.push( {id: 8,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 9,  orient: "v", len: 286,   lpos: aw + fw,                               vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 10, orient: "h", len: 305,   lpos: aw * 2 + fw,                           vpos: aw + fw                             });
            b.push( {id: 11, orient: "v", len: 262,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw                             });
            b.push( {id: 12, orient: "h", len: 48,                                                 vpos: aw + fw + b[11].len - dw            });
                                                b[12].lpos = aw * 2 + fw + b[10].len - b[12].len;  
            b.push( {id: 13, orient: "v", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len                 });
            b.push( {id: 14, orient: "h", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 15, orient: "v", len: 262,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 16, orient: "h", len: 113,   lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len + b[9].len - dw    });
            b.push( {id: 17, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len + b[15].len - dw });
            b.push( {id: 18, orient: "h", len: 190.5, lpos: aw * 3 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len+ b[15].len - dw  });
            b.push( {id: 19, orient: "v", len: 37.5,  lpos: aw + b[4].len,                         vpos: b[1].len - dw                                    });
            b.push( {id: 20, orient: "h", len: 208,   lpos: aw * 2 + b[4].len,                     vpos: b[3].len - dw                                    });
            b.push( {id: 21, orient: "v", len: 68,    lpos: aw * 2 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 22, orient: "h", len: 173,   lpos: aw * 3 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 23, orient: "v", len: 68,    lpos: aw * 3 + fw + b[4].len + b[22].len,    vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 24, orient: "h", len: 173,   lpos: aw * 3 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len + b[23].len - dw });
            b.push( {id: 25, orient: "v", len: 37 });
            b.push( {id: 26, orient: "h", len: 34 });
            b.push( {id: 27, orient: "v", len: 37 });
            b.push( {id: 28, orient: "h", len: 34 });
            b.push( {id: 29, orient: "v", len: 37 });
            b.push( {id: 30, orient: "h", len: 34 });
            b.push( {id: 31, orient: "v", len: 37 });
            b.push( {id: 32, orient: "h", len: 34 });
            b.push( {id: 33, orient: "v", len: 37 });
            b.push( {id: 34, orient: "h", len: 34 });
            b.push( {id: 35, orient: "v", len: 37 });
            b.push( {id: 36, orient: "h", len: 34 });
            var hspace = (b[10].len - b[26].len - aw * 2) / 2;
            var vspace = (b[11].len + b[13].len + b[15].len - aw * 2 - b[25].len - b[27].len - b[29].len) / 4;
            b[25].lpos = aw * 2 + fw + hspace;                    b[25].vpos = aw * 2 + fw + vspace;
            b[26].lpos = aw * 3 + fw + hspace;                    b[26].vpos = aw * 2 + fw + vspace;
            b[27].lpos = aw * 3 + fw + hspace + b[26].len;        b[27].vpos = aw * 2 + fw + vspace;
            b[28].lpos = aw * 3 + fw + hspace;                    b[28].vpos = aw * 2 + fw + vspace + b[25].len - dw;
            b[29].lpos = aw * 2 + fw + hspace;                    b[29].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[30].lpos = aw * 3 + fw + hspace;                    b[30].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[31].lpos = aw * 3 + fw + hspace + b[30].len;        b[31].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[32].lpos = aw * 3 + fw + hspace;                    b[32].vpos = aw * 2 + fw + vspace * 2 + b[25].len + b[29].len - dw ;
            b[33].lpos = aw * 2 + fw + hspace;                    b[33].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[34].lpos = aw * 3 + fw + hspace;                    b[34].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[35].lpos = aw * 3 + fw + hspace + b[34].len;        b[35].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[36].lpos = aw * 3 + fw + hspace;                    b[36].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len + b[33].len - dw ;
            break;
        case "5A20": 
            pageTitle = "5 Bedroom House - Elevation A - 20 inch Footer";
            scale = 1.25;
            dw = 3.5;
            fw = 20;
            b.push( {id:0 }); // dummy 
            b.push( {id: 1,  orient: "v", len: 659,   lpos: 0,                                     vpos: 0                                   });
            b.push( {id: 2,  orient: "h", len: 344,   lpos: aw,                                    vpos: 0                                   });
            b.push( {id: 3,  orient: "v", len: 695,   lpos: aw + b[2].len,                         vpos: 0                                   });
            b.push( {id: 4,  orient: "h", len: 130.5, lpos: aw,                                    vpos: b[1].len - dw                       });
            b.push( {id: 5,  orient: "v", len: 284,   lpos: aw + fw,                               vpos: aw + fw                             });
            b.push( {id: 6,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len - dw             });
            b.push( {id: 7,  orient: "v", len: 48,    lpos: aw * 2 + fw + b[6].len - dw,           vpos: aw + fw + b[5].len                  });
            b.push( {id: 8,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 9,  orient: "v", len: 284,   lpos: aw + fw,                               vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 10, orient: "h", len: 301,   lpos: aw * 2 + fw,                           vpos: aw + fw                             });
            b.push( {id: 11, orient: "v", len: 260,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw                             });
            b.push( {id: 12, orient: "h", len: 48,                                                 vpos: aw + fw + b[11].len - dw            });
                                                b[12].lpos = aw * 2 + fw + b[10].len - b[12].len;  
            b.push( {id: 13, orient: "v", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len                 });
            b.push( {id: 14, orient: "h", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 15, orient: "v", len: 260,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 16, orient: "h", len: 109,   lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len + b[9].len - dw    });
            b.push( {id: 17, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len + b[15].len - dw });
            b.push( {id: 18, orient: "h", len: 190.5, lpos: aw * 3 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len+ b[15].len - dw  });
            b.push( {id: 19, orient: "v", len: 37.5,  lpos: aw + b[4].len,                         vpos: b[1].len - dw                                    });
            b.push( {id: 20, orient: "h", len: 212,   lpos: aw * 2 + b[4].len,                     vpos: b[3].len - dw                                    });
            b.push( {id: 21, orient: "v", len: 64,    lpos: aw * 2 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 22, orient: "h", len: 169,   lpos: aw * 3 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 23, orient: "v", len: 64,    lpos: aw * 3 + fw + b[4].len + b[22].len,    vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 24, orient: "h", len: 169,   lpos: aw * 3 + fw + b[4].len,                vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len + b[23].len - dw });
            b.push( {id: 25, orient: "v", len: 37 });
            b.push( {id: 26, orient: "h", len: 34 });
            b.push( {id: 27, orient: "v", len: 37 });
            b.push( {id: 28, orient: "h", len: 34 });
            b.push( {id: 29, orient: "v", len: 37 });
            b.push( {id: 30, orient: "h", len: 34 });
            b.push( {id: 31, orient: "v", len: 37 });
            b.push( {id: 32, orient: "h", len: 34 });
            b.push( {id: 33, orient: "v", len: 37 });
            b.push( {id: 34, orient: "h", len: 34 });
            b.push( {id: 35, orient: "v", len: 37 });
            b.push( {id: 36, orient: "h", len: 34 });
            var hspace = (b[10].len - b[26].len - aw * 2) / 2;
            var vspace = (b[11].len + b[13].len + b[15].len - aw * 2 - b[25].len - b[27].len - b[29].len) / 4;
            b[25].lpos = aw * 2 + fw + hspace;                    b[25].vpos = aw * 2 + fw + vspace;
            b[26].lpos = aw * 3 + fw + hspace;                    b[26].vpos = aw * 2 + fw + vspace;
            b[27].lpos = aw * 3 + fw + hspace + b[26].len;        b[27].vpos = aw * 2 + fw + vspace;
            b[28].lpos = aw * 3 + fw + hspace;                    b[28].vpos = aw * 2 + fw + vspace + b[25].len - dw;
            b[29].lpos = aw * 2 + fw + hspace;                    b[29].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[30].lpos = aw * 3 + fw + hspace;                    b[30].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[31].lpos = aw * 3 + fw + hspace + b[30].len;        b[31].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[32].lpos = aw * 3 + fw + hspace;                    b[32].vpos = aw * 2 + fw + vspace * 2 + b[25].len + b[29].len - dw ;
            b[33].lpos = aw * 2 + fw + hspace;                    b[33].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[34].lpos = aw * 3 + fw + hspace;                    b[34].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[35].lpos = aw * 3 + fw + hspace + b[34].len;        b[35].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[36].lpos = aw * 3 + fw + hspace;                    b[36].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len + b[33].len - dw ;
            break;
        case "5B16": 
            pageTitle = "5 Bedroom House - Elevation B - 16 inch Footer";
            scale = 1.25;
            dw = 3.5;
            fw = 16;
            b.push( {id:0 }); // dummy 
            b.push( {id: 1,  orient: "v", len: 691,   lpos: 0,                                     vpos: 0                                   });
            b.push( {id: 2,  orient: "h", len: 340,   lpos: aw,                                    vpos: 0                                   });
            b.push( {id: 3,  orient: "v", len: 691,   lpos: aw + b[2].len,                         vpos: 0                                   });
            b.push( {id: 4,  orient: "h", len: 340,   lpos: aw,                                    vpos: b[1].len - dw                       });
            b.push( {id: 5,  orient: "v", len: 286,   lpos: aw + fw,                               vpos: aw + fw                             });
            b.push( {id: 6,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len - dw             });
            b.push( {id: 7,  orient: "v", len: 48,    lpos: aw * 2 + fw + b[6].len - dw,           vpos: aw + fw + b[5].len                  });
            b.push( {id: 8,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 9,  orient: "v", len: 286,   lpos: aw + fw,                               vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 10, orient: "h", len: 305,   lpos: aw * 2 + fw,                           vpos: aw + fw                             });
            b.push( {id: 11, orient: "v", len: 262,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw                             });
            b.push( {id: 12, orient: "h", len: 48,                                                 vpos: aw + fw + b[11].len - dw            });
                                                b[12].lpos = aw * 2 + fw + b[10].len - b[12].len;  
            b.push( {id: 13, orient: "v", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len                 });
            b.push( {id: 14, orient: "h", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 15, orient: "v", len: 262,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 16, orient: "h", len: 113,   lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len + b[9].len - dw    });
            b.push( {id: 17, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len + b[15].len - dw });
            b.push( {id: 18, orient: "h", len: 190.5, lpos: aw * 3 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len+ b[15].len - dw  });
            b.push( {id: 19, orient: "v", len: 20,    lpos: aw + fw,                               vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len     });
            b.push( {id: 20, orient: "h", len: 130.5, lpos: aw * 2 + fw,                           vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len     });
            b.push( {id: 21, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[20].len,               vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 22, orient: "h", len: 173,   lpos: aw * 3 + fw + b[20].len,               vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 23, orient: "v", len: 68,    lpos: aw * 3 + fw + b[20].len + b[22].len,   vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 24, orient: "h", len: 305,   lpos: aw * 2 + fw,                           vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len + b[19].len - dw });
            b.push( {id: 25, orient: "v", len: 37 });
            b.push( {id: 26, orient: "h", len: 34 });
            b.push( {id: 27, orient: "v", len: 37 });
            b.push( {id: 28, orient: "h", len: 34 });
            b.push( {id: 29, orient: "v", len: 37 });
            b.push( {id: 30, orient: "h", len: 34 });
            b.push( {id: 31, orient: "v", len: 37 });
            b.push( {id: 32, orient: "h", len: 34 });
            b.push( {id: 33, orient: "v", len: 37 });
            b.push( {id: 34, orient: "h", len: 34 });
            b.push( {id: 35, orient: "v", len: 37 });
            b.push( {id: 36, orient: "h", len: 34 });
            var hspace = (b[10].len - b[26].len - aw * 2) / 2;
            var vspace = (b[11].len + b[13].len + b[15].len - aw * 2 - b[25].len - b[27].len - b[29].len) / 4;
            b[25].lpos = aw * 2 + fw + hspace;                    b[25].vpos = aw * 2 + fw + vspace;
            b[26].lpos = aw * 3 + fw + hspace;                    b[26].vpos = aw * 2 + fw + vspace;
            b[27].lpos = aw * 3 + fw + hspace + b[26].len;        b[27].vpos = aw * 2 + fw + vspace;
            b[28].lpos = aw * 3 + fw + hspace;                    b[28].vpos = aw * 2 + fw + vspace + b[25].len - dw;
            b[29].lpos = aw * 2 + fw + hspace;                    b[29].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[30].lpos = aw * 3 + fw + hspace;                    b[30].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[31].lpos = aw * 3 + fw + hspace + b[30].len;        b[31].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[32].lpos = aw * 3 + fw + hspace;                    b[32].vpos = aw * 2 + fw + vspace * 2 + b[25].len + b[29].len - dw ;
            b[33].lpos = aw * 2 + fw + hspace;                    b[33].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[34].lpos = aw * 3 + fw + hspace;                    b[34].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[35].lpos = aw * 3 + fw + hspace + b[34].len;        b[35].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[36].lpos = aw * 3 + fw + hspace;                    b[36].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len + b[33].len - dw ;

            break;
        case "5B20": 
            pageTitle = "5 Bedroom House - Elevation B - 20 inch Footer";
            scale = 1.25;
            dw = 3.5;
            fw = 20;
            b.push( {id:0 }); // dummy 
            b.push( {id: 1,  orient: "v", len: 695,   lpos: 0,                                     vpos: 0                                   });
            b.push( {id: 2,  orient: "h", len: 344,   lpos: aw,                                    vpos: 0                                   });
            b.push( {id: 3,  orient: "v", len: 695,   lpos: aw + b[2].len,                         vpos: 0                                   });
            b.push( {id: 4,  orient: "h", len: 344,   lpos: aw,                                    vpos: b[1].len - dw                       });
            b.push( {id: 5,  orient: "v", len: 284,   lpos: aw + fw,                               vpos: aw + fw                             });
            b.push( {id: 6,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len - dw             });
            b.push( {id: 7,  orient: "v", len: 48,    lpos: aw * 2 + fw + b[6].len - dw,           vpos: aw + fw + b[5].len                  });
            b.push( {id: 8,  orient: "h", len: 48,    lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 9,  orient: "v", len: 284,   lpos: aw + fw,                               vpos: aw + fw + b[5].len + b[7].len       });
            b.push( {id: 10, orient: "h", len: 301,   lpos: aw * 2 + fw,                           vpos: aw + fw                             });
            b.push( {id: 11, orient: "v", len: 260,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw                             });
            b.push( {id: 12, orient: "h", len: 48,                                                 vpos: aw + fw + b[11].len - dw            });
                                                b[12].lpos = aw * 2 + fw + b[10].len - b[12].len;  
            b.push( {id: 13, orient: "v", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len                 });
            b.push( {id: 14, orient: "h", len: 48,    lpos: aw * 2 + fw + b[10].len - b[12].len,   vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 15, orient: "v", len: 260,   lpos: aw * 2 + fw + b[10].len,               vpos: aw + fw + b[11].len + b[13].len     });
            b.push( {id: 16, orient: "h", len: 109,   lpos: aw * 2 + fw,                           vpos: aw + fw + b[5].len + b[7].len + b[9].len - dw    });
            b.push( {id: 17, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len + b[15].len - dw });
            b.push( {id: 18, orient: "h", len: 190.5, lpos: aw * 3 + fw + b[16].len,               vpos: aw + fw + b[11].len + b[13].len+ b[15].len - dw  });
            b.push( {id: 19, orient: "v", len: 16,    lpos: aw + fw,                               vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len     });
            b.push( {id: 20, orient: "h", len: 130.5, lpos: aw * 2 + fw,                           vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len     });
            b.push( {id: 21, orient: "v", len: 49.5,  lpos: aw * 2 + fw + b[20].len,               vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 22, orient: "h", len: 169,   lpos: aw * 3 + fw + b[20].len,               vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 23, orient: "v", len: 64,    lpos: aw * 3 + fw + b[20].len + b[22].len,   vpos: aw + fw * 2 + b[11].len + b[13].len + b[15].len  });
            b.push( {id: 24, orient: "h", len: 301,   lpos: aw * 2 + fw,                           vpos: aw + fw * 2 + b[5].len + b[7].len + b[9].len + b[19].len - dw });
            b.push( {id: 25, orient: "v", len: 37 });
            b.push( {id: 26, orient: "h", len: 34 });
            b.push( {id: 27, orient: "v", len: 37 });
            b.push( {id: 28, orient: "h", len: 34 });
            b.push( {id: 29, orient: "v", len: 37 });
            b.push( {id: 30, orient: "h", len: 34 });
            b.push( {id: 31, orient: "v", len: 37 });
            b.push( {id: 32, orient: "h", len: 34 });
            b.push( {id: 33, orient: "v", len: 37 });
            b.push( {id: 34, orient: "h", len: 34 });
            b.push( {id: 35, orient: "v", len: 37 });
            b.push( {id: 36, orient: "h", len: 34 });
            var hspace = (b[10].len - b[26].len - aw * 2) / 2;
            var vspace = (b[11].len + b[13].len + b[15].len - aw * 2 - b[25].len - b[27].len - b[29].len) / 4;
            b[25].lpos = aw * 2 + fw + hspace;                    b[25].vpos = aw * 2 + fw + vspace;
            b[26].lpos = aw * 3 + fw + hspace;                    b[26].vpos = aw * 2 + fw + vspace;
            b[27].lpos = aw * 3 + fw + hspace + b[26].len;        b[27].vpos = aw * 2 + fw + vspace;
            b[28].lpos = aw * 3 + fw + hspace;                    b[28].vpos = aw * 2 + fw + vspace + b[25].len - dw;
            b[29].lpos = aw * 2 + fw + hspace;                    b[29].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[30].lpos = aw * 3 + fw + hspace;                    b[30].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[31].lpos = aw * 3 + fw + hspace + b[30].len;        b[31].vpos = aw * 2 + fw + vspace * 2 + b[25].len;
            b[32].lpos = aw * 3 + fw + hspace;                    b[32].vpos = aw * 2 + fw + vspace * 2 + b[25].len + b[29].len - dw ;
            b[33].lpos = aw * 2 + fw + hspace;                    b[33].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[34].lpos = aw * 3 + fw + hspace;                    b[34].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[35].lpos = aw * 3 + fw + hspace + b[34].len;        b[35].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len;
            b[36].lpos = aw * 3 + fw + hspace;                    b[36].vpos = aw * 2 + fw + vspace * 3 + b[25].len + b[29].len + b[33].len - dw ;
            break;

    }
}
